version: '2.2'

services:
  web:
    environment:
      # Update this to your default AzuraCast domain.
      # DON'T FORGET TO UPDATE THE nginx_proxy SERVICE BELOW!
      VIRTUAL_HOST: azuracast.localhost
      # To enable automated LetsEncrypt certificates and renewal, uncomment the lines below
      #   and set the domain name to the same as the one above. You can also optionally provide
      #   an e-mail address for expiration notifications.
      # LETSENCRYPT_HOST: azuracast.local
      # LETSENCRYPT_EMAIL: your-email-address@example.com
    volumes:
      - /var/azuracast/media:/var/azuracast/stations/media/udon
  
  stations:
    volumes:
      - /var/azuracast/media:/var/azuracast/stations/media/udon

  udon-front:
    image: udon-front:latest
    ports:
      - '5000:5000'
    environment:
      VIRTUAL_HOST: site.localhost
      VIRTUAL_PORT: 5000
    restart: always

  udon-back:
    image: udon-back:latest
    ports:
      - '5001:5001'
    environment:
      VIRTUAL_HOST: back.localhost
      VIRTUAL_PORT: 5001
    restart: always

  nginx_proxy:
    image: azuracast/azuracast_nginx_proxy:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - letsencrypt:/etc/nginx/certs
      - nginx_proxy_vhosts:/etc/nginx/vhost.d
      - letsencrypt_html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      # Update this to your default AzuraCast domain.
      DEFAULT_HOST: site.localhost
    depends_on:
      - web
      - udon-front
    restart: always

  nginx_proxy_letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    volumes_from:
      - nginx_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

volumes:
  letsencrypt_html: {}
  nginx_proxy_vhosts: {}
